/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LibMS.Frames;

import com.LibMS.Common.DBConnect;
import com.LibMS.Common.SystemLogger;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author B.M.D.C.Bandara
 */
public class AddEmployee extends javax.swing.JFrame {

    boolean allDone = false;
    private static final AddEmployee INSTANCE = new AddEmployee();

    /**
     * Creates new form AddEmployee
     */
    private AddEmployee() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            SystemLogger.initLogger(AddEmployee.class).error("Exception from class constructor", ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        setImage();
        setDataToComboBox();
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        lab_image = new javax.swing.JLabel();
        panel_addEmp = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        rb_active = new javax.swing.JRadioButton();
        rb_inactive = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cb_role = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_add_home = new javax.swing.JTextField();
        txt_add_street = new javax.swing.JTextField();
        txt_add_zone = new javax.swing.JTextField();
        txt_add_city = new javax.swing.JTextField();
        txt_add_postal = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Employee Window");
        setUndecorated(true);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Add Employee");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 260, 40));
        jLayeredPane1.add(lab_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 768));

        panel_addEmp.setBackground(new java.awt.Color(255, 255, 255));
        panel_addEmp.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Status");

        rb_active.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_active);
        rb_active.setText("Active");
        rb_active.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_activeKeyPressed(evt);
            }
        });

        rb_inactive.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_inactive);
        rb_inactive.setText("Inactive");
        rb_inactive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_inactiveKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Role");

        cb_role.setBackground(new java.awt.Color(255, 255, 255));
        cb_role.setOpaque(false);
        cb_role.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_roleKeyPressed(evt);
            }
        });

        jButton1.setText("Add ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Postal Code");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("City");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Zone");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Street");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("Home Name / No.");

        txt_add_home.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_home.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_homeKeyPressed(evt);
            }
        });

        txt_add_street.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_streetKeyPressed(evt);
            }
        });

        txt_add_zone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_zone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_zoneKeyPressed(evt);
            }
        });

        txt_add_city.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_cityKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_cityKeyTyped(evt);
            }
        });

        txt_add_postal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_postal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_postalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_postalKeyTyped(evt);
            }
        });

        jLayeredPane3.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_home, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_street, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_zone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_city, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_postal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_add_city, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txt_add_zone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_add_street, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_add_home, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_add_postal))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_zone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Primary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Date of Birth");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("NIC Number");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("First Name");

        txt_fname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fnameKeyPressed(evt);
            }
        });

        txt_lname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lnameKeyPressed(evt);
            }
        });

        txt_nic.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nicKeyPressed(evt);
            }
        });

        txt_phone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_phoneKeyPressed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setOpaque(false);
        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyPressed(evt);
            }
        });

        rb_male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb_male);
        rb_male.setText("Male");
        rb_male.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_maleKeyPressed(evt);
            }
        });

        rb_female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb_female);
        rb_female.setText("Female");
        rb_female.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_femaleKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Gender");

        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_fname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_lname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_nic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_phone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jDateChooser1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(rb_male, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(rb_female, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(rb_male)
                        .addGap(80, 80, 80)
                        .addComponent(rb_female)))
                .addGap(39, 39, 39))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_female)
                    .addComponent(rb_male)
                    .addComponent(jLabel8)))
        );

        panel_addEmp.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(rb_active, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(rb_inactive, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(cb_role, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel_addEmp.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel_addEmpLayout = new javax.swing.GroupLayout(panel_addEmp);
        panel_addEmp.setLayout(panel_addEmpLayout);
        panel_addEmpLayout.setHorizontalGroup(
            panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addEmpLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_addEmpLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_addEmpLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(127, 127, 127)
                            .addGroup(panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel_addEmpLayout.createSequentialGroup()
                                    .addComponent(rb_active)
                                    .addGap(59, 59, 59)
                                    .addComponent(rb_inactive))))
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(195, 195, 195))
        );
        panel_addEmpLayout.setVerticalGroup(
            panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addEmpLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addEmpLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_addEmpLayout.createSequentialGroup()
                        .addComponent(cb_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_active)
                            .addComponent(rb_inactive))))
                .addGap(29, 29, 29)
                .addGroup(panel_addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jLayeredPane1.add(panel_addEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 966, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addEmp();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_fnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_fname.getText().trim().equals("")) {
            txt_lname.grabFocus();
        }
    }//GEN-LAST:event_txt_fnameKeyPressed

    private void txt_lnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_lname.getText().trim().equals("")) {
            txt_nic.grabFocus();
        }
    }//GEN-LAST:event_txt_lnameKeyPressed

    private void txt_nicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nicKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_nic.getText().trim().equals("")) {
            txt_phone.grabFocus();
        }
    }//GEN-LAST:event_txt_nicKeyPressed

    private void txt_phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_phone.getText().trim().equals("")) {
            jDateChooser1.grabFocus();
        }
    }//GEN-LAST:event_txt_phoneKeyPressed

    private void cb_roleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_roleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && cb_role.getSelectedIndex() != 0) {
            rb_active.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            cb_role.setSelectedIndex(cb_role.getSelectedIndex());
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            cb_role.setSelectedIndex(cb_role.getSelectedIndex());
        } else {
            //cb_role.grabFocus();
            //cb_role.setPopupVisible(true);
            cb_role.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cb_roleKeyPressed

    private void rb_activeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_activeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rb_active.setSelected(true);
            jButton1.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            rb_inactive.grabFocus();
        }
    }//GEN-LAST:event_rb_activeKeyPressed

    private void rb_inactiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_inactiveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rb_inactive.setSelected(true);
            jButton1.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            rb_active.grabFocus();
        }
    }//GEN-LAST:event_rb_inactiveKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //new EmployeeManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_add_homeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_homeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_home.getText().trim().equals("")) {
            txt_add_street.grabFocus();
        }
    }//GEN-LAST:event_txt_add_homeKeyPressed

    private void txt_add_streetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_streetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_street.getText().trim().equals("")) {
            txt_add_zone.grabFocus();
        }
    }//GEN-LAST:event_txt_add_streetKeyPressed

    private void txt_add_zoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_zoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_zone.getText().trim().equals("")) {
            txt_add_city.grabFocus();
        }
    }//GEN-LAST:event_txt_add_zoneKeyPressed

    private void txt_add_cityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_cityKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_city.getText().trim().equals("")) {
            txt_add_postal.grabFocus();
        }
    }//GEN-LAST:event_txt_add_cityKeyPressed

    private void txt_add_cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_cityKeyTyped
        if (!(Character.getType(evt.getKeyChar()) == 1 || Character.getType(evt.getKeyChar()) == 2)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_add_cityKeyTyped

    private void txt_add_postalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_postalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_postal.getText().trim().equals("")) {
            cb_role.grabFocus();
            cb_role.setPopupVisible(true);
            cb_role.setSelectedIndex(0);
        }
    }//GEN-LAST:event_txt_add_postalKeyPressed

    private void txt_add_postalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_postalKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_add_postalKeyTyped

    private void jDateChooser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            rb_male.grabFocus();
        }
    }//GEN-LAST:event_jDateChooser1KeyPressed

    private void rb_maleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_maleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            rb_female.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_add_home.grabFocus();
        }
    }//GEN-LAST:event_rb_maleKeyPressed

    private void rb_femaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_femaleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            rb_male.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_add_home.grabFocus();
        }
    }//GEN-LAST:event_rb_femaleKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddEmployee().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_role;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lab_image;
    private javax.swing.JLayeredPane panel_addEmp;
    private javax.swing.JRadioButton rb_active;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_inactive;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JTextField txt_add_city;
    private javax.swing.JTextField txt_add_home;
    private javax.swing.JTextField txt_add_postal;
    private javax.swing.JTextField txt_add_street;
    private javax.swing.JTextField txt_add_zone;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables

    private void setImage() {
        try {
            String path = "pics/addemp.jpg";
            Image image = ImageIO.read(new FileInputStream(path));
            image = image.getScaledInstance(lab_image.getWidth(), lab_image.getHeight(), Image.SCALE_SMOOTH);
            lab_image.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    private void setDataToComboBox() {
        try {
            ResultSet search = DBConnect.search("select * from role");
            cb_role.addItem("    ");
            while (search.next()) {
                cb_role.addItem(search.getString("roletype"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(AddEmployee.class).error("Exception from SELECT query in setDataToComboBox()", ex);
        }
    }

    private String getDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
    }

    private void addEmp() {
        if (checkContents()) {
            String fname = txt_fname.getText().toLowerCase();
            String lname = txt_lname.getText().toLowerCase();
            String nic = txt_nic.getText().toLowerCase();
            String phone = txt_phone.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dob = dateFormat.format(jDateChooser1.getDate());
            String gender = (rb_male.isSelected()) ? "M" : "F";
            String home = txt_add_home.getText().toLowerCase();
            String street = txt_add_street.getText().toLowerCase();
            String zone = txt_add_zone.getText().toLowerCase();
            String city = txt_add_city.getText().toLowerCase();
            String postal = txt_add_postal.getText();
            String comboSelection = cb_role.getItemAt(cb_role.getSelectedIndex());
            int role = 0;
            try {
                ResultSet search = DBConnect.search("select * from role where roletype='" + comboSelection + "'");
                if (search.next()) {
                    role = search.getInt("id");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                SystemLogger.initLogger(AddEmployee.class).error("Exception from SELECT query", ex);
            }
            int stat = (rb_active.isSelected()) ? 1 : 0;
            try {
                DBConnect.iud("insert into employee(role_id,fname,lname,nic,phone,dob,gender,home,street,zone,city,postalcode"
                        + ",stat,dateemployeed) values('" + role + "','" + fname + "','" + lname + "','" + nic + "','" + phone + "'"
                        + ",'" + dob + "','" + gender + "','" + home + "','" + street + "','" + zone + "','" + city + "','" + postal + "','" + stat + "'"
                        + ",'" + getDate() + "')");
            } catch (ClassNotFoundException | SQLException ex) {
                SystemLogger.initLogger(AddEmployee.class).error("Exception from INSERT query", ex);
            }
            clearFields();
        }
    }

    private boolean checkContents() {
        if (txt_fname.getText().trim().equals("")) {
            txt_fname.grabFocus();
            allDone = false;
        } else if (txt_lname.getText().trim().equals("")) {
            txt_lname.grabFocus();
            allDone = false;
        } else if (txt_nic.getText().trim().equals("") || !(txt_nic.getText().trim().length() == 10 || txt_nic.getText().trim().length() == 12)) {
            txt_nic.grabFocus();
            allDone = false;
        } else if (txt_phone.getText().trim().equals("") || txt_phone.getText().trim().length() != 10) {
            txt_phone.grabFocus();
            allDone = false;
        } else if (txt_add_home.getText().trim().equals("")) {
            txt_add_home.grabFocus();
            allDone = false;
        } else if (txt_add_street.getText().trim().equals("")) {
            txt_add_street.grabFocus();
            allDone = false;
        } else if (txt_add_zone.getText().trim().equals("")) {
            txt_add_zone.grabFocus();
            allDone = false;
        } else if (txt_add_city.getText().trim().equals("")) {
            txt_add_city.grabFocus();
            allDone = false;
        } else if (txt_add_postal.getText().trim().equals("") || txt_add_postal.getText().trim().length() != 5) {
            txt_add_postal.grabFocus();
            allDone = false;
        } else if (cb_role.getSelectedIndex() == 0) {
            cb_role.grabFocus();
            cb_role.setPopupVisible(true);
            allDone = false;
        } else {
            allDone = true;
        }
        return allDone;
    }

    private void clearFields() {
        txt_fname.setText(null);
        txt_lname.setText(null);
        txt_nic.setText(null);
        txt_phone.setText(null);
        cb_role.setSelectedIndex(0);
        rb_active.setSelected(true);
        jDateChooser1.setDate(null);
        rb_male.setSelected(true);
        txt_add_home.setText(null);
        txt_add_street.setText(null);
        txt_add_zone.setText(null);
        txt_add_city.setText(null);
        txt_add_postal.setText(null);
    }

    public static AddEmployee getInstance() {
        return INSTANCE;
    }
}
