/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LibMS.Frames;

import com.LibMS.Common.DBConnect;
import com.LibMS.Common.SystemLogger;
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author B.M.D.C.Bandara
 */
public class AddViewEmployee extends javax.swing.JFrame {

    boolean allDone;
    int empId;

    /**
     * Creates new form EmployeeManagement
     */
    public AddViewEmployee() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            SystemLogger.initLogger(AddViewEmployee.class).error("Exception from class constructor", ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        setImage();
        panel_updateEmp.setVisible(false);
        setColumnSizes();
        loadTableData();
        setDataToComboBox();
        setButtons();
        jButton3.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panel_main = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lab_image = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_viewEmp = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        cb_searchCategory = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panel_updateEmp = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        rb_active = new javax.swing.JRadioButton();
        rb_inactive = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cb_role = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rb_female = new javax.swing.JRadioButton();
        rb_male = new javax.swing.JRadioButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_add_home = new javax.swing.JTextField();
        txt_add_street = new javax.swing.JTextField();
        txt_add_zone = new javax.swing.JTextField();
        txt_add_city = new javax.swing.JTextField();
        txt_add_postal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management Window");
        setUndecorated(true);
        setResizable(false);

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setForeground(new java.awt.Color(51, 51, 51));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Management");
        panel_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 240, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Employee ");
        panel_main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 50));
        panel_main.add(lab_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 768));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_viewEmp.setOpaque(true);
        panel_viewEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ROLE", "FIRST NAME", "LAST NAME", "GENDER", "DATE OF BIRTH", "NIC No.", "MOBILE No.", "STATUS", "DATE EMPLOYEED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(20);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        panel_viewEmp.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 920, 390));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setText("Add New Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_viewEmp.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 185, 41));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setText("View/Update Employee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_viewEmp.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, 230, 42));

        txt_search.setText("Search");
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchFocusLost(evt);
            }
        });
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        panel_viewEmp.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 180, 30));

        cb_searchCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIC", "First Name", "Last Name", "Mobile No." }));
        panel_viewEmp.add(cb_searchCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 80, 30));

        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 255));
        jButton5.setText("Home");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_viewEmp.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 153));
        jButton6.setText("Employee");
        jButton6.setEnabled(false);
        panel_viewEmp.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel_viewEmp.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 10, 35));

        jLayeredPane1.add(panel_viewEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 966, 768));

        panel_updateEmp.setOpaque(true);
        panel_updateEmp.setPreferredSize(new java.awt.Dimension(1016, 768));
        panel_updateEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Status");
        panel_updateEmp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 130, 30));

        rb_active.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_active);
        rb_active.setText("Active");
        panel_updateEmp.add(rb_active, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, -1, -1));

        rb_inactive.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_inactive);
        rb_inactive.setText("Inactive");
        panel_updateEmp.add(rb_inactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Role");
        panel_updateEmp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 130, 20));

        panel_updateEmp.add(cb_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 280, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Update Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_updateEmp.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 141, 42));

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_updateEmp.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 114, 42));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel_updateEmp.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 640, 12, 42));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Primary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("First Name");

        txt_fname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txt_lname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("NIC Number");

        txt_nic.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txt_phone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Phone Number");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Date of Birth");

        txt_dob.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Gender");

        rb_female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb_female);
        rb_female.setText("Female");

        rb_male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb_male);
        rb_male.setText("Male");

        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_fname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_lname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_nic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_phone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txt_dob, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(rb_female, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(rb_male, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(160, 160, 160)
                        .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(159, 159, 159)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_lname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(159, 159, 159)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(rb_male)
                                .addGap(53, 53, 53)
                                .addComponent(rb_female))
                            .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_male)
                        .addComponent(jLabel9))
                    .addComponent(rb_female))
                .addGap(30, 30, 30))
        );

        panel_updateEmp.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 610, 230));

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Postal Code");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("City");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Zone");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Street");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("Home Name / No.");

        txt_add_home.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_home.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_homeKeyPressed(evt);
            }
        });

        txt_add_street.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_streetKeyPressed(evt);
            }
        });

        txt_add_zone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_zone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_zoneKeyPressed(evt);
            }
        });

        txt_add_city.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_cityKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_cityKeyTyped(evt);
            }
        });

        txt_add_postal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_add_postal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_add_postalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_postalKeyTyped(evt);
            }
        });

        jLayeredPane3.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_home, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_street, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_zone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_city, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_add_postal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_add_city, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txt_add_zone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txt_add_street, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txt_add_home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txt_add_postal, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_zone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panel_updateEmp.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 610, 210));

        jLayeredPane1.add(panel_updateEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 966, 768));

        panel_main.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTable1.getSelectedRow() != -1 && jTable1.getSelectedRowCount() == 1) {
            panel_viewEmp.setVisible(false);
            panel_updateEmp.setVisible(true);

            this.empId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());

            String fname = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
            txt_fname.setText(fname);

            String lname = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
            txt_lname.setText(lname);

            String nic = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
            txt_nic.setText(nic);

            String phone = jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString();
            txt_phone.setText(phone);

            try {
                ResultSet search = DBConnect.search("select * from employee where id='" + empId + "'");
                if (search.first()) {
                    txt_dob.setText(search.getString("dob"));
                    if (search.getString("gender").equals("M")) {
                        rb_male.setSelected(true);
                    } else {
                        rb_female.setSelected(true);
                    }
                    txt_add_home.setText(search.getString("home"));
                    txt_add_street.setText(search.getString("street"));
                    txt_add_zone.setText(search.getString("zone"));
                    txt_add_city.setText(search.getString("city"));
                    txt_add_postal.setText(search.getString("postalcode"));
                }
            } catch (ClassNotFoundException | SQLException ex) {
                SystemLogger.initLogger(AddViewEmployee.class).error("Exception from SELECT query", ex);
            }

            String role = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            switch (role) {
                case "DIR":
                    cb_role.setSelectedIndex(1);
                    break;
                case "TECH":
                    cb_role.setSelectedIndex(2);
                    break;
                case "ASSIS_LIB":
                    cb_role.setSelectedIndex(3);
                    break;
                case "LIB_AID":
                    cb_role.setSelectedIndex(4);
                    break;
                default:
                    break;
            }

            if (jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString().equals("Active")) {
                rb_active.setSelected(true);
            } else {
                rb_inactive.setSelected(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Select an employee from the table to view / update.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panel_updateEmp.setVisible(false);
        panel_viewEmp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AddEmployee.getInstance().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateEmp();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_add_homeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_homeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_home.getText().trim().equals("")) {
            txt_add_street.grabFocus();
        }
    }//GEN-LAST:event_txt_add_homeKeyPressed

    private void txt_add_streetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_streetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_street.getText().trim().equals("")) {
            txt_add_zone.grabFocus();
        }
    }//GEN-LAST:event_txt_add_streetKeyPressed

    private void txt_add_zoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_zoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_zone.getText().trim().equals("")) {
            txt_add_city.grabFocus();
        }
    }//GEN-LAST:event_txt_add_zoneKeyPressed

    private void txt_add_cityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_cityKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_city.getText().trim().equals("")) {
            txt_add_postal.grabFocus();
        }
    }//GEN-LAST:event_txt_add_cityKeyPressed

    private void txt_add_cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_cityKeyTyped
        if (!(Character.getType(evt.getKeyChar()) == 1 || Character.getType(evt.getKeyChar()) == 2)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_add_cityKeyTyped

    private void txt_add_postalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_postalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !txt_add_postal.getText().trim().equals("")) {
            cb_role.grabFocus();
            cb_role.setPopupVisible(true);
            cb_role.setSelectedIndex(0);
        }
    }//GEN-LAST:event_txt_add_postalKeyPressed

    private void txt_add_postalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_postalKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_add_postalKeyTyped

    private void txt_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusLost
        txt_search.setText("Search");
    }//GEN-LAST:event_txt_searchFocusLost

    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
        txt_search.setText(null);
    }//GEN-LAST:event_txt_searchFocusGained

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        searchEmp();
    }//GEN-LAST:event_txt_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddViewEmployee().setVisible(true);
        });
    }

    private void setImage() {
        try {
            String path = "pics/emp2.jpg";
            Image image = ImageIO.read(new FileInputStream(path));
            image = image.getScaledInstance(lab_image.getWidth(), lab_image.getHeight(), Image.SCALE_SMOOTH);
            lab_image.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_role;
    private javax.swing.JComboBox<String> cb_searchCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lab_image;
    private javax.swing.JLayeredPane panel_main;
    private javax.swing.JLayeredPane panel_updateEmp;
    private javax.swing.JLayeredPane panel_viewEmp;
    private javax.swing.JRadioButton rb_active;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_inactive;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JTextField txt_add_city;
    private javax.swing.JTextField txt_add_home;
    private javax.swing.JTextField txt_add_postal;
    private javax.swing.JTextField txt_add_street;
    private javax.swing.JTextField txt_add_zone;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    private void loadTableData() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
            ResultSet search = DBConnect.search("select * from employee");
            while (search.next()) {
                Vector v = new Vector();
                v.add(search.getInt("id"));
                ResultSet search1 = DBConnect.search("select * from role where id='" + search.getInt("role_id") + "'");
                String roleType = null;
                if (search1.next()) {
                    roleType = search1.getString("roletype");
                }
                v.add(roleType);
                v.add(search.getString("fname"));
                v.add(search.getString("lname"));
                if (search.getString("gender").equals("M")) {
                    v.add("Male");
                } else {
                    v.add("Female");
                }
                v.add(search.getString("dob"));
                v.add(search.getString("nic"));
                v.add(search.getString("phone"));
                String stat = (search.getInt("stat") == 1) ? "Active" : "Inactive";
                v.add(stat);
                v.add(search.getString("dateemployeed"));
                dtm.addRow(v);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(AddViewEmployee.class).error("", ex);
        }
    }

    private void setDataToComboBox() {
        try {
            ResultSet search = DBConnect.search("select * from role");
            cb_role.addItem("    ");
            while (search.next()) {
                cb_role.addItem(search.getString("roletype"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(AddViewEmployee.class).error("", ex);
        }
    }

    private void updateEmp() {
        if (checkContents()) {
            String fname = txt_fname.getText().toLowerCase();
            String lname = txt_lname.getText().toLowerCase();
            String nic = txt_nic.getText().toLowerCase();
            String phone = txt_phone.getText();
            String comboSelection = cb_role.getItemAt(cb_role.getSelectedIndex());
            String gender = (rb_male.isSelected()) ? "M" : "F";
            String dob = txt_dob.getText();
            String home = txt_add_home.getText().toLowerCase();
            String street = txt_add_street.getText().toLowerCase();
            String zone = txt_add_zone.getText().toLowerCase();
            String city = txt_add_city.getText().toLowerCase();
            String postal = txt_add_postal.getText();
            int role = 0;
            try {
                ResultSet search = DBConnect.search("select * from role where roletype='" + comboSelection + "'");
                if (search.next()) {
                    role = search.getInt("id");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                SystemLogger.initLogger(AddViewEmployee.class).error("Exception from SELECT query", ex);
            }
            int stat = (rb_active.isSelected()) ? 1 : 0;
            try {
                DBConnect.iud("update employee set role_id='" + role + "',fname='" + fname + "',"
                        + "lname='" + lname + "',nic='" + nic + "',phone='" + phone + "',dob='" + dob + "',"
                        + "gender='" + gender + "',home='" + home + "',street='" + street + "',zone='" + zone + "',"
                        + "city='" + city + "',postalcode='" + postal + "',stat='" + stat + "' where id='" + empId + "'");
            } catch (ClassNotFoundException | SQLException ex) {
                SystemLogger.initLogger(AddViewEmployee.class).error("Exception from UPDATE query", ex);
            }
            JOptionPane.showMessageDialog(rootPane, "Successfull !");
            new AddViewEmployee().setVisible(true);
            this.dispose();
        }
    }

    private boolean checkContents() {
        if (txt_fname.getText().trim().equals("")) {
            txt_fname.grabFocus();
            allDone = false;
        } else if (txt_lname.getText().trim().equals("")) {
            txt_lname.grabFocus();
            allDone = false;
        } else if (txt_nic.getText().trim().equals("") || !(txt_nic.getText().trim().length() == 10 || txt_nic.getText().trim().length() == 12)) {
            txt_nic.grabFocus();
            allDone = false;
        } else if (txt_phone.getText().trim().equals("") || txt_phone.getText().trim().length() != 10) {
            txt_phone.grabFocus();
            allDone = false;
        } else if (txt_dob.getText().trim().equals("") || txt_dob.getText().trim().length() != 10) {
            txt_dob.grabFocus();
            allDone = false;
        } else if (txt_add_home.getText().trim().equals("")) {
            txt_add_home.grabFocus();
            allDone = false;
        } else if (txt_add_street.getText().trim().equals("")) {
            txt_add_street.grabFocus();
            allDone = false;
        } else if (txt_add_zone.getText().trim().equals("")) {
            txt_add_zone.grabFocus();
            allDone = false;
        } else if (txt_add_city.getText().trim().equals("")) {
            txt_add_city.grabFocus();
            allDone = false;
        } else if (txt_add_postal.getText().trim().equals("") || txt_add_postal.getText().trim().length() != 5) {
            txt_add_postal.grabFocus();
            allDone = false;
        } else if (cb_role.getSelectedIndex() == 0) {
            cb_role.grabFocus();
            cb_role.setPopupVisible(true);
            allDone = false;
        } else {
            allDone = true;
        }
        return allDone;
    }

    void setButtons() {
        jButton5.setOpaque(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setBorderPainted(false);
        jButton6.setOpaque(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setBorderPainted(false);
    }

    private void searchEmp() {
        String searchCategory = cb_searchCategory.getSelectedItem().toString();
        String searchString = txt_search.getText().toLowerCase();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        jTable1.clearSelection();

        switch (searchCategory) {
            case "NIC":
                for (int row = 0; row < dtm.getRowCount(); row++) {
                    if (dtm.getValueAt(row, 6).toString().contains(searchString)) {
                        jTable1.getSelectionModel().addSelectionInterval(row, row);
                        
                    }
                }   break;
            case "First Name":
                for (int row = 0; row < dtm.getRowCount(); row++) {
                    if (dtm.getValueAt(row, 2).toString().contains(searchString)) {
                        jTable1.getSelectionModel().addSelectionInterval(row, row);
                        
                    }
                }   break;
            case "Last Name":
                for (int row = 0; row < dtm.getRowCount(); row++) {
                    if (dtm.getValueAt(row, 3).toString().contains(searchString)) {
                        jTable1.getSelectionModel().addSelectionInterval(row, row);
                        
                    }
                }   break;
            default:
                for (int row = 0; row < dtm.getRowCount(); row++) {
                    if (dtm.getValueAt(row, 7).toString().contains(searchString)) {
                        jTable1.getSelectionModel().addSelectionInterval(row, row);
                        
                    }
                }   break;
        }
        
        if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "No match found!");
        }
    }

    private void setColumnSizes() {
        //jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);

        jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(renderer);

        jTable1.getColumnModel().getColumn(1).setMaxWidth(60);
        jTable1.getColumnModel().getColumn(1).setMinWidth(60);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(60);
        jTable1.getColumnModel().getColumn(8).setMinWidth(60);
        //jTable1.getColumnModel().getColumn(6).setCellRenderer(renderer);
    }
}
