/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LibMS.Frames;

import com.LibMS.Common.DBConnect;
import com.LibMS.Common.SystemData;
import com.LibMS.Common.SystemLogger;
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author B.M.D.C.Bandara
 */
public class LendBook extends javax.swing.JFrame {

    int memID;
    boolean allDoneLend;

    /**
     * Creates new form LendBook
     */
    public LendBook() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            SystemLogger.initLogger(LendBook.class).error("Exception from class constructor", ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        sp_isbn.setVisible(false);
        sp_memNIC.setVisible(false);
        setImage();
        txt_memId.setEditable(false);
        //jCalendar1.setMinSelectableDate(new Date());
        Date upperLimit = new Date(new Date().getTime() + (1000l * 60l * 60l * 24l * 30l * 6l));
        jCalendar1.setSelectableDateRange(new Date(), upperLimit);
        setButtons();
        txt_isbn.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        lab_image = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        sp_memNIC = new javax.swing.JScrollPane();
        list_memNIC = new javax.swing.JList<>();
        sp_isbn = new javax.swing.JScrollPane();
        list_isbn = new javax.swing.JList<>();
        txt_isbn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_memNIC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_memId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        but_lendBook = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lend Book Window");
        setUndecorated(true);
        setResizable(false);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Lend Book");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 50));
        jLayeredPane1.add(lab_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 768));

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setMaximumSize(new java.awt.Dimension(966, 768));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(966, 768));
        jLayeredPane2.setName(""); // NOI18N
        jLayeredPane2.setOpaque(true);
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(966, 768));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setMaximumSize(new java.awt.Dimension(966, 768));
        jLayeredPane3.setMinimumSize(new java.awt.Dimension(966, 768));
        jLayeredPane3.setPreferredSize(new java.awt.Dimension(966, 768));
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list_memNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                list_memNICKeyPressed(evt);
            }
        });
        sp_memNIC.setViewportView(list_memNIC);

        jLayeredPane3.add(sp_memNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 350, -1));

        list_isbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                list_isbnKeyPressed(evt);
            }
        });
        sp_isbn.setViewportView(list_isbn);

        jLayeredPane3.add(sp_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 350, -1));

        txt_isbn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_isbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_isbnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_isbnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_isbnKeyTyped(evt);
            }
        });
        jLayeredPane3.add(txt_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 350, 28));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("ISBN Number");
        jLayeredPane3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 133, 28));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Member NIC No.");
        jLayeredPane3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 133, 28));

        txt_memNIC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_memNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_memNICKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_memNICKeyReleased(evt);
            }
        });
        jLayeredPane3.add(txt_memNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 350, 28));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Member ID");
        jLayeredPane3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 133, 28));

        txt_memId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLayeredPane3.add(txt_memId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 350, 28));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Due Date");
        jLayeredPane3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 133, 28));

        but_lendBook.setBackground(new java.awt.Color(255, 255, 255));
        but_lendBook.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        but_lendBook.setText("Lend Book");
        but_lendBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_lendBookActionPerformed(evt);
            }
        });
        jLayeredPane3.add(but_lendBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 170, 42));
        jLayeredPane3.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 350, 200));

        jButton2.setBackground(new java.awt.Color(51, 123, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 150, 42));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 10, 40));

        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 255));
        jButton7.setText("Home");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 10, 35));

        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 153, 153));
        jButton8.setText("Lend Book");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        jLayeredPane2.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 966, 768));

        jLayeredPane1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 966, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_memNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_memNICKeyReleased
        loadMemNIC();
    }//GEN-LAST:event_txt_memNICKeyReleased

    private void txt_isbnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_isbnKeyReleased
        loadIsbn();
    }//GEN-LAST:event_txt_isbnKeyReleased

    private void txt_memNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_memNICKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            list_memNIC.grabFocus();
            list_memNIC.setSelectedIndex(0);
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (list_memNIC.getFirstVisibleIndex() != -1) {
                list_memNIC.grabFocus();
                list_memNIC.setSelectedIndex(0);
            } else {
                String message = "Member Not Found. Add as a new member?";
                String title = "Member Not Found";
                int option = JOptionPane.showOptionDialog(rootPane, message, title,
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, JOptionPane.OK_OPTION);
                if (option == JOptionPane.OK_OPTION) {
                    AddViewMember add = new AddViewMember();
                    add.but_addMem.doClick();
                    add.setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_txt_memNICKeyPressed

    private void txt_isbnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_isbnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            list_isbn.grabFocus();
            list_isbn.setSelectedIndex(0);
        }
    }//GEN-LAST:event_txt_isbnKeyPressed

    private void list_isbnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list_isbnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_isbn.setText(list_isbn.getSelectedValue().substring(0, list_isbn.getSelectedValue().indexOf("-")));
            sp_isbn.setVisible(false);
            txt_memNIC.grabFocus();
        }
    }//GEN-LAST:event_list_isbnKeyPressed

    private void list_memNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list_memNICKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_memNIC.setText(list_memNIC.getSelectedValue().substring(0, list_memNIC.getSelectedValue().indexOf("-")));
            try {
                ResultSet search = DBConnect.search("select id from member where nic = '" + txt_memNIC.getText() + "'");
                if (search.next()) {
                    txt_memId.setText(Integer.toString(search.getInt("id")));
                }
            } catch (ClassNotFoundException | SQLException ex) {
                SystemLogger.initLogger(LendBook.class).error("Exception from SELECT query", ex);
            }
            sp_memNIC.setVisible(false);
            jCalendar1.grabFocus();
        }
    }//GEN-LAST:event_list_memNICKeyPressed

    private void txt_isbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_isbnKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_isbnKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new AddViewBooks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void but_lendBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_lendBookActionPerformed
        lendBook();
    }//GEN-LAST:event_but_lendBookActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LendBook().setVisible(true);
        });
    }

    private void setImage() {
        try {
            String path = "pics/lendbook3.jpg";
            Image image = ImageIO.read(new FileInputStream(path));
            image = image.getScaledInstance(lab_image.getWidth(), lab_image.getHeight(), Image.SCALE_SMOOTH);
            lab_image.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_lendBook;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lab_image;
    private javax.swing.JList<String> list_isbn;
    private javax.swing.JList<String> list_memNIC;
    private javax.swing.JScrollPane sp_isbn;
    private javax.swing.JScrollPane sp_memNIC;
    public javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_memId;
    public javax.swing.JTextField txt_memNIC;
    // End of variables declaration//GEN-END:variables

    private void loadMemNIC() {
        sp_memNIC.setVisible(true);
        String searchTxt = txt_memNIC.getText();
        String query = "SELECT * FROM member WHERE nic LIKE '" + searchTxt + "%'";
        try {
            ResultSet search = DBConnect.search(query);
            Vector v = new Vector();
            list_memNIC.setModel(new DefaultListModel());
            while (search.next()) {
                v.add(search.getString("nic") + "-" + search.getString("lname"));
            }
            list_memNIC.setListData(v);
        } catch (ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(LendBook.class).error("Exception from SELECT query", ex);
        }
    }

    private void loadIsbn() {
        sp_isbn.setVisible(true);
        String searchTxt = txt_isbn.getText();
        String query = "SELECT * FROM book WHERE isbn LIKE '" + searchTxt + "%' and availableqty!=0";
        try {
            ResultSet search = DBConnect.search(query);
            Vector v = new Vector();
            list_isbn.setModel(new DefaultListModel());
            while (search.next()) {
                v.add(search.getString("isbn") + "-" + search.getString("name"));
            }
            list_isbn.setListData(v);
        } catch (ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(LendBook.class).error("Exception from SELECT query", ex);
        }
    }

    private void lendBook() {
        if (lendCheckContents()) {
            String isbn = txt_isbn.getText();
            int member_id = Integer.parseInt(txt_memId.getText());
            Date date = jCalendar1.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String due_date = sdf.format(date);
            String sysuser = Integer.toString(SystemData.getSysUserId());

            String query = "insert into lendbook(book_isbn,member_id,lend_date,due_date,sysuser_id)"
                    + " values('" + isbn + "','" + member_id + "',CURDATE(),'" + due_date + "','" + sysuser + "')";
            try {
                DBConnect.iud(query);
                DBConnect.iud("UPDATE book set availableqty=availableqty-1 where isbn='"+isbn+"'");
            } catch (ClassNotFoundException | SQLException ex) {
                SystemLogger.initLogger(LendBook.class).error("Exception from UPDATE query", ex);
            }
            JOptionPane.showMessageDialog(rootPane, "Successful!");
            clearFields();
        }
    }

    private boolean lendCheckContents() {
        if (txt_isbn.getText().trim().equals("") || !(txt_isbn.getText().trim().length() == 13)) {
            txt_isbn.grabFocus();
            allDoneLend = false;
        } else if (txt_memNIC.getText().trim().equals("") || !(txt_memNIC.getText().trim().length() == 10 || txt_memNIC.getText().trim().length() == 12)) {
            txt_memNIC.grabFocus();
            allDoneLend = false;
        } else {
            allDoneLend = true;
        }
        return allDoneLend;
    }

    void setButtons(){
        jButton7.setOpaque(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setBorderPainted(false);
        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setBorderPainted(false);
    }
    
    private void clearFields() {
        txt_isbn.setText(null);
        txt_memId.setText(null);
        txt_memNIC.setText(null);
        jCalendar1.setDate(new Date());
    }
}
