/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LibMS.Frames;

import com.LibMS.Common.DBConnect;
import com.LibMS.Common.SystemLogger;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author B.M.D.C.Bandara
 */
public class ReportGenarator extends javax.swing.JFrame {

    /**
     * Creates new form ReportGenarator
     */
    public ReportGenarator() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("Exception from class constructor", ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        setButtons();
        jLabel1.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Layer_dir = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(17, 184, 218));
        kGradientPanel1.setkStartColor(new java.awt.Color(17, 184, 218));
        kGradientPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new Color(1.0f,1.0f,1.0f,0.6f));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Store Report");

        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLayeredPane2.setBackground(new Color(1.0f,1.0f,1.0f,0.6f));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLayeredPane2.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane2MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("List Report");

        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jLayeredPane6.setBackground(new Color(1.0f,1.0f,1.0f,0.6f));
        jLayeredPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLayeredPane6.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane6.setPreferredSize(new java.awt.Dimension(189, 159));
        jLayeredPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane6MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pending");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Resubmissions");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Report");

        jLayeredPane6.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLayeredPane7.setBackground(new Color(1.0f,1.0f,1.0f,0.6f));
        jLayeredPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLayeredPane7.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane7MouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("System User");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("List Report");

        jLayeredPane7.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane5.setBackground(new Color(1.0f,1.0f,1.0f,0.6f));
        jLayeredPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLayeredPane5.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane5MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lending");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Report");

        jLayeredPane5.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLayeredPane4.setBackground(new Color(1.0f,1.0f,1.0f,0.6f));
        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLayeredPane4.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane4MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Memberwise");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data / Lending Report");

        jLayeredPane4.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLayeredPane3.setBackground(new Color(1.0f,1.0f,1.0f,0.6f));
        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLayeredPane3.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane3MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Member ");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("List");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Report");

        jLayeredPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLayeredPane8.setBackground(new Color(1.0f,1.0f,1.0f,0.6f));
        jLayeredPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLayeredPane8.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPane8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayeredPane8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayeredPane8MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Outdated");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Re-");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Submissions");

        jLayeredPane8.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addGroup(jLayeredPane8Layout.createSequentialGroup()
                        .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addContainerGap())))
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Layer_dir.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layer_dir.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layer_dir.setLayer(jLayeredPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layer_dir.setLayer(jLayeredPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layer_dir.setLayer(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layer_dir.setLayer(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layer_dir.setLayer(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layer_dir.setLayer(jLayeredPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Layer_dirLayout = new javax.swing.GroupLayout(Layer_dir);
        Layer_dir.setLayout(Layer_dirLayout);
        Layer_dirLayout.setHorizontalGroup(
            Layer_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Layer_dirLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(Layer_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Layer_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Layer_dirLayout.createSequentialGroup()
                        .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane8))
                    .addGroup(Layer_dirLayout.createSequentialGroup()
                        .addComponent(jLayeredPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Layer_dirLayout.createSequentialGroup()
                        .addComponent(jLayeredPane5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane4)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        Layer_dirLayout.setVerticalGroup(
            Layer_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Layer_dirLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(Layer_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Layer_dirLayout.createSequentialGroup()
                        .addGroup(Layer_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Layer_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Layer_dirLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Layer_dirLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(Layer_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLayeredPane7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane8))
                .addGap(0, 67, Short.MAX_VALUE))
        );

        kGradientPanel1.add(Layer_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 70, 770, 610));

        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Home");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 204, 204));
        jButton8.setText("Report Viewer");
        jButton8.setEnabled(false);
        kGradientPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        kGradientPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 10, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLayeredPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseEntered
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        jLabel3.setForeground(new Color(64, 64, 64));
    }//GEN-LAST:event_jLayeredPane1MouseEntered

    private void jLayeredPane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseExited
        jLayeredPane1.setOpaque(false);
        jLayeredPane1.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        jLabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLayeredPane1MouseExited

    private void jLayeredPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane2MouseEntered
        jLayeredPane2.setOpaque(true);
        jLayeredPane2.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        jLabel1.setForeground(new Color(64, 64, 64));
        jLabel2.setForeground(new Color(64, 64, 64));
    }//GEN-LAST:event_jLayeredPane2MouseEntered

    private void jLayeredPane2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane2MouseExited
        jLayeredPane2.setOpaque(false);
        jLayeredPane2.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        jLabel1.setForeground(Color.WHITE);
        jLabel2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLayeredPane2MouseExited

    private void jLayeredPane6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane6MouseEntered
        jLayeredPane6.setOpaque(true);
        jLayeredPane6.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        jLabel12.setForeground(new Color(64, 64, 64));
        jLabel11.setForeground(new Color(64, 64, 64));
        jLabel18.setForeground(new Color(64, 64, 64));
    }//GEN-LAST:event_jLayeredPane6MouseEntered

    private void jLayeredPane6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane6MouseExited
        jLayeredPane6.setOpaque(false);
        jLayeredPane6.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        jLabel11.setForeground(Color.WHITE);
        jLabel12.setForeground(Color.WHITE);
        jLabel18.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLayeredPane6MouseExited

    private void jLayeredPane7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane7MouseEntered
        jLayeredPane7.setOpaque(true);
        jLayeredPane7.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        jLabel13.setForeground(new Color(64, 64, 64));
        jLabel14.setForeground(new Color(64, 64, 64));
    }//GEN-LAST:event_jLayeredPane7MouseEntered

    private void jLayeredPane7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane7MouseExited
        jLayeredPane7.setOpaque(false);
        jLayeredPane7.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        jLabel13.setForeground(Color.WHITE);
        jLabel14.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLayeredPane7MouseExited

    private void jLayeredPane5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane5MouseEntered
        jLayeredPane5.setOpaque(true);
        jLayeredPane5.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        jLabel6.setForeground(new Color(64, 64, 64));
        jLabel7.setForeground(new Color(64, 64, 64));
    }//GEN-LAST:event_jLayeredPane5MouseEntered

    private void jLayeredPane5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane5MouseExited
        jLayeredPane5.setOpaque(false);
        jLayeredPane5.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        jLabel6.setForeground(Color.WHITE);
        jLabel7.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLayeredPane5MouseExited

    private void jLayeredPane4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane4MouseEntered
        jLayeredPane4.setOpaque(true);
        jLayeredPane4.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        jLabel4.setForeground(new Color(64, 64, 64));
        jLabel5.setForeground(new Color(64, 64, 64));
    }//GEN-LAST:event_jLayeredPane4MouseEntered

    private void jLayeredPane4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane4MouseExited
        jLayeredPane4.setOpaque(false);
        jLayeredPane4.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        jLabel4.setForeground(Color.WHITE);
        jLabel5.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLayeredPane4MouseExited

    private void jLayeredPane3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane3MouseEntered
        jLayeredPane3.setOpaque(true);
        jLayeredPane3.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        jLabel8.setForeground(new Color(64, 64, 64));
        jLabel9.setForeground(new Color(64, 64, 64));
        jLabel10.setForeground(new Color(64, 64, 64));
    }//GEN-LAST:event_jLayeredPane3MouseEntered

    private void jLayeredPane3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane3MouseExited
        jLayeredPane3.setOpaque(false);
        jLayeredPane3.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        jLabel8.setForeground(Color.WHITE);
        jLabel9.setForeground(Color.WHITE);
        jLabel10.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLayeredPane3MouseExited

    private void jLayeredPane8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane8MouseEntered
        jLayeredPane8.setOpaque(true);
        jLayeredPane8.setBackground(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        jLabel15.setForeground(new Color(64, 64, 64));
        jLabel16.setForeground(new Color(64, 64, 64));
        jLabel17.setForeground(new Color(64, 64, 64));
    }//GEN-LAST:event_jLayeredPane8MouseEntered

    private void jLayeredPane8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane8MouseExited
        jLayeredPane8.setOpaque(false);
        jLayeredPane8.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        jLabel15.setForeground(Color.WHITE);
        jLabel16.setForeground(Color.WHITE);
        jLabel17.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLayeredPane8MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLayeredPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane2MouseClicked
        try {
            String path = "C:\\Users\\B.M.D.C.Bandara\\Documents\\NetBeansProjects\\LibraryManagementSystem\\reports\\EmployeeListReport.jrxml";
            JREmptyDataSource emptyDS = new JREmptyDataSource();
            JasperReport compiledRep = JasperCompileManager.compileReport(path);
            JasperPrint fillRepo = JasperFillManager.fillReport(compiledRep, null, DBConnect.getCon());
            JasperViewer.viewReport(fillRepo, false);
        } catch (JRException | ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("", ex);
        }
        
    }//GEN-LAST:event_jLayeredPane2MouseClicked

    private void jLayeredPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane3MouseClicked
        try {
            String path = "C:\\Users\\B.M.D.C.Bandara\\Documents\\NetBeansProjects\\LibraryManagementSystem\\reports\\MemListReport.jrxml";
            JREmptyDataSource emptyDS = new JREmptyDataSource();
            JasperReport compiledRep = JasperCompileManager.compileReport(path);
            JasperPrint fillRepo = JasperFillManager.fillReport(compiledRep, null, DBConnect.getCon());
            JasperViewer.viewReport(fillRepo, false);
        } catch (JRException | ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("", ex);
        }
    }//GEN-LAST:event_jLayeredPane3MouseClicked

    private void jLayeredPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseClicked
        try {
            String path = "C:\\Users\\B.M.D.C.Bandara\\Documents\\NetBeansProjects\\LibraryManagementSystem\\reports\\BookListReport.jrxml";
            JREmptyDataSource emptyDS = new JREmptyDataSource();
            JasperReport compiledRep = JasperCompileManager.compileReport(path);
            JasperPrint fillRepo = JasperFillManager.fillReport(compiledRep, null, DBConnect.getCon());
            JasperViewer.viewReport(fillRepo, false);
        } catch (JRException | ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("", ex);
        }
    }//GEN-LAST:event_jLayeredPane1MouseClicked

    private void jLayeredPane7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane7MouseClicked
        try {
            String path = "C:\\Users\\B.M.D.C.Bandara\\Documents\\NetBeansProjects\\LibraryManagementSystem\\reports\\SysUserListReport.jrxml";
            JREmptyDataSource emptyDS = new JREmptyDataSource();
            JasperReport compiledRep = JasperCompileManager.compileReport(path);
            JasperPrint fillRepo = JasperFillManager.fillReport(compiledRep, null, DBConnect.getCon());
            JasperViewer.viewReport(fillRepo, false);
        } catch (JRException | ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("", ex);
        }
    }//GEN-LAST:event_jLayeredPane7MouseClicked

    private void jLayeredPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane6MouseClicked
        try {
            String path = "C:\\Users\\B.M.D.C.Bandara\\Documents\\NetBeansProjects\\LibraryManagementSystem\\reports\\PendingResubReport.jrxml";
            JREmptyDataSource emptyDS = new JREmptyDataSource();
            JasperReport compiledRep = JasperCompileManager.compileReport(path);
            JasperPrint fillRepo = JasperFillManager.fillReport(compiledRep, null, DBConnect.getCon());
            JasperViewer.viewReport(fillRepo, false);
        } catch (JRException | ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("", ex);
        }
    }//GEN-LAST:event_jLayeredPane6MouseClicked

    private void jLayeredPane8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane8MouseClicked
        try {
            String path = "C:\\Users\\B.M.D.C.Bandara\\Documents\\NetBeansProjects\\LibraryManagementSystem\\reports\\OutdatedResubReport.jrxml";
            JREmptyDataSource emptyDS = new JREmptyDataSource();
            JasperReport compiledRep = JasperCompileManager.compileReport(path);
            JasperPrint fillRepo = JasperFillManager.fillReport(compiledRep, null, DBConnect.getCon());
            JasperViewer.viewReport(fillRepo, false);
        } catch (JRException | ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("", ex);
        }
    }//GEN-LAST:event_jLayeredPane8MouseClicked

    private void jLayeredPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane5MouseClicked
        try {
            String path = "C:\\Users\\B.M.D.C.Bandara\\Documents\\NetBeansProjects\\LibraryManagementSystem\\reports\\LendingReport.jrxml";
            JREmptyDataSource emptyDS = new JREmptyDataSource();
            JasperReport compiledRep = JasperCompileManager.compileReport(path);
            JasperPrint fillRepo = JasperFillManager.fillReport(compiledRep, null, DBConnect.getCon());
            JasperViewer.viewReport(fillRepo, false);
        } catch (JRException | ClassNotFoundException | SQLException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("", ex);
        }
    }//GEN-LAST:event_jLayeredPane5MouseClicked

    private void jLayeredPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane4MouseClicked
        new AddViewMember().setVisible(true);
    }//GEN-LAST:event_jLayeredPane4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            SystemLogger.initLogger(ReportGenarator.class).error("", ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReportGenarator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layer_dir;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JSeparator jSeparator3;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

    void setButtons() {
        jButton7.setOpaque(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setBorderPainted(false);
        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setBorderPainted(false);
    }

}
